// Reads recipes/*.md and writes site/data.js as `window.RECIPES = [...]`.
// Using a .js file (not .json) means the site loads when opened directly from
// the filesystem (file://) without a server — and works the same on GitHub Pages.

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import matter from "gray-matter";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RECIPES_DIR = path.join(ROOT, "recipes");
const OUT = path.join(ROOT, "site", "data.js");

const LANGS = ["en", "de"];

// Pull "- item" lines that follow a "## <name>" heading until the next heading.
function sectionLines(body, heading) {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const re = new RegExp(`^##\\s+${escaped}\\s*$`, "im");
  const start = body.search(re);
  if (start === -1) return [];
  const after = body.slice(start).split(/\r?\n/).slice(1);
  const out = [];
  for (const raw of after) {
    if (/^##\s+/.test(raw)) break;
    const line = raw.replace(/^\s*(?:[-*]|\d+\.)\s+/, "").trim();
    if (line) out.push(line);
  }
  return out;
}

// Resolve a translatable text field for one language, with sensible fallback.
// A recipe declares its source language via `lang` (default "en"); the unsuffixed
// `title` / "## Ingredients" / "## Steps" hold that source-language content, while
// `title_de`, "## Ingredients (de)", etc. hold a translation.
function pickText(data, content, lang) {
  const out = {};
  for (const L of LANGS) {
    const titled = data[`title_${L}`] || (lang === L ? data.title : "") || "";
    let ing = sectionLines(content, `Ingredients (${L})`);
    let steps = sectionLines(content, `Steps (${L})`);
    if (!ing.length && lang === L) ing = sectionLines(content, "Ingredients");
    if (!steps.length && lang === L) steps = sectionLines(content, "Steps");
    out[L] = { title: titled, ingredients: ing, steps };
  }
  // Fall back to the other language so nothing renders blank before translation.
  const other = (L) => (L === "en" ? "de" : "en");
  for (const L of LANGS) {
    const o = other(L);
    if (!out[L].title) out[L].title = out[o].title;
    if (!out[L].ingredients.length) out[L].ingredients = out[o].ingredients;
    if (!out[L].steps.length) out[L].steps = out[o].steps;
  }
  return out;
}

async function main() {
  let files = [];
  try {
    files = (await readdir(RECIPES_DIR)).filter((f) => f.endsWith(".md"));
  } catch {
    files = [];
  }

  const recipes = [];
  for (const file of files) {
    const slug = file.replace(/\.md$/, "");
    const raw = await readFile(path.join(RECIPES_DIR, file), "utf8");
    const { data, content } = matter(raw);
    const lang = String(data.lang || "en").toLowerCase();
    const text = pickText(data, content, lang);
    recipes.push({
      slug,
      lang,
      title: { en: text.en.title || slug, de: text.de.title || slug },
      source: data.source || "",
      image: data.image || "",
      servings: data.servings || "",
      time_minutes: data.time_minutes || null,
      tags: data.tags || {},
      added_by: data.added_by || "",
      notes: data.notes || "",
      needs_review: Boolean(data.needs_review),
      ingredients: { en: text.en.ingredients, de: text.de.ingredients },
      steps: { en: text.en.steps, de: text.de.steps },
    });
  }

  recipes.sort((a, b) => a.title.en.localeCompare(b.title.en));

  await mkdir(path.dirname(OUT), { recursive: true });
  const banner = "// AUTO-GENERATED by scripts/build.mjs — do not edit by hand.\n";
  await writeFile(OUT, `${banner}window.RECIPES = ${JSON.stringify(recipes, null, 2)};\n`, "utf8");
  console.log(`Built ${recipes.length} recipe(s) -> site/data.js`);
}

main().catch((err) => {
  console.error("Build failed:", err.message);
  process.exit(1);
});
