// Reads recipes/*.md and writes site/data.js as `window.RECIPES = [...]`.
// Using a .js file (not .json) means the site loads when opened directly from
// the filesystem (file://) without a server — and works the same on GitHub Pages.

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import matter from "gray-matter";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RECIPES_DIR = path.join(ROOT, "recipes");
const OUT = path.join(ROOT, "site", "data.js");

// Pull "- item" lines that follow a "## <name>" heading until the next heading.
function sectionLines(body, heading) {
  const re = new RegExp(`^##\\s+${heading}\\s*$`, "im");
  const start = body.search(re);
  if (start === -1) return [];
  const after = body.slice(start).split(/\r?\n/).slice(1);
  const out = [];
  for (const raw of after) {
    if (/^##\s+/.test(raw)) break;
    const line = raw.replace(/^\s*(?:[-*]|\d+\.)\s+/, "").trim();
    if (line) out.push(line);
  }
  return out;
}

async function main() {
  let files = [];
  try {
    files = (await readdir(RECIPES_DIR)).filter((f) => f.endsWith(".md"));
  } catch {
    files = [];
  }

  const recipes = [];
  for (const file of files) {
    const slug = file.replace(/\.md$/, "");
    const raw = await readFile(path.join(RECIPES_DIR, file), "utf8");
    const { data, content } = matter(raw);
    recipes.push({
      slug,
      title: data.title || slug,
      source: data.source || "",
      image: data.image || "",
      servings: data.servings || "",
      time_minutes: data.time_minutes || null,
      tags: data.tags || {},
      added_by: data.added_by || "",
      notes: data.notes || "",
      needs_review: Boolean(data.needs_review),
      ingredients: sectionLines(content, "Ingredients"),
      steps: sectionLines(content, "Steps"),
    });
  }

  recipes.sort((a, b) => a.title.localeCompare(b.title));

  await mkdir(path.dirname(OUT), { recursive: true });
  const banner = "// AUTO-GENERATED by scripts/build.mjs — do not edit by hand.\n";
  await writeFile(OUT, `${banner}window.RECIPES = ${JSON.stringify(recipes, null, 2)};\n`, "utf8");
  console.log(`Built ${recipes.length} recipe(s) -> site/data.js`);
}

main().catch((err) => {
  console.error("Build failed:", err.message);
  process.exit(1);
});
